### ISSUE TITLE
Step Changed

### ISSUE THREAD

**Issue by Lightjohn** [emmt/TiPi#2]
This error occur when running lbfgs on any input after 1/2 iteration:
`TiPi: TotalVariationDeconvolution An error has occurred: Step changed`
Activating lower bound/positivity choose another algorithm and in this case it's working.

**Comment by emmt** [comment]
The bug was in non-linear conjugate gradient, not LBFGS. It has been fixed by commit `0b6d7cd9d5c7f428e154ee1a889f1bc2e7921c57` on Thu Oct 6 19:51:35 2016 +0200
